module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'adac-core',
        'adac-cli',
        'adac-diagram',
        'adac-parser',
        'adac-schema',
        'adac-layout',
        'adac-layout-core',
        'adac-layout-elk',
        'adac-layout-dagre',
        'adac-icons-aws',
        'adac-icons-gcp',
        'adac-icons-azure',
        'adac-compliance',
        'adac-cost',
        'adac-export-terraform',
        'adac-export-k8s',
        'adac-export-cloudformation',
        'adac-doc',
        'adac-templates',
        'adac-optimizer',
        'adac-web',
        'adac-web-server',
        'adac-vscode',
      ],
    ],
    'subject-case': [2, 'never', ['start-case', 'pascal-case', 'upper-case']],
  },
};
