import type { CostCategory, PricingModel } from '../types/index.js';

export interface PricingEntry {
  serviceType: string;
  displayName: string;
  category: CostCategory;
  defaultMonthly: number;
  pricingModel: PricingModel;
  unit: string;
  description: string;
}

/**
 * AWS pricing data — estimated monthly costs for common service types.
 * Values are based on typical on-demand pricing in us-east-1.
 */
export const awsPricingData: Record<string, PricingEntry> = {
  ec2: {
    serviceType: 'ec2',
    displayName: 'EC2',
    category: 'compute',
    defaultMonthly: 30.37,
    pricingModel: 'on-demand',
    unit: 'instance-hour',
    description: 't3.medium',
  },
  'ecs-fargate': {
    serviceType: 'ecs-fargate',
    displayName: 'ECS Fargate',
    category: 'compute',
    defaultMonthly: 36.86,
    pricingModel: 'on-demand',
    unit: 'task-hour',
    description: '1vCPU, 2GB',
  },
  lambda: {
    serviceType: 'lambda',
    displayName: 'Lambda',
    category: 'compute',
    defaultMonthly: 6.0,
    pricingModel: 'on-demand',
    unit: 'invocations',
    description: '10M requests',
  },
  s3: {
    serviceType: 's3',
    displayName: 'S3',
    category: 'storage',
    defaultMonthly: 23.0,
    pricingModel: 'on-demand',
    unit: 'GB-month',
    description: '1TB standard',
  },
  'rds-mysql': {
    serviceType: 'rds-mysql',
    displayName: 'RDS MySQL',
    category: 'database',
    defaultMonthly: 49.64,
    pricingModel: 'on-demand',
    unit: 'instance-hour',
    description: 'db.t3.medium',
  },
  'rds-postgres': {
    serviceType: 'rds-postgres',
    displayName: 'RDS PostgreSQL',
    category: 'database',
    defaultMonthly: 49.64,
    pricingModel: 'on-demand',
    unit: 'instance-hour',
    description: 'db.t3.medium',
  },
  dynamodb: {
    serviceType: 'dynamodb',
    displayName: 'DynamoDB',
    category: 'database',
    defaultMonthly: 25.0,
    pricingModel: 'on-demand',
    unit: 'read/write units',
    description: 'On-demand',
  },
  sqs: {
    serviceType: 'sqs',
    displayName: 'SQS',
    category: 'messaging',
    defaultMonthly: 0.4,
    pricingModel: 'on-demand',
    unit: 'messages',
    description: '1M messages',
  },
  sns: {
    serviceType: 'sns',
    displayName: 'SNS',
    category: 'messaging',
    defaultMonthly: 0.5,
    pricingModel: 'on-demand',
    unit: 'publishes',
    description: '1M publishes',
  },
  'api-gateway-rest': {
    serviceType: 'api-gateway-rest',
    displayName: 'API Gateway',
    category: 'networking',
    defaultMonthly: 3.5,
    pricingModel: 'on-demand',
    unit: 'API calls',
    description: '1M REST calls',
  },
  cloudfront: {
    serviceType: 'cloudfront',
    displayName: 'CloudFront',
    category: 'networking',
    defaultMonthly: 8.5,
    pricingModel: 'on-demand',
    unit: 'GB-transfer',
    description: '100GB/mo',
  },
  route53: {
    serviceType: 'route53',
    displayName: 'Route 53',
    category: 'networking',
    defaultMonthly: 0.5,
    pricingModel: 'on-demand',
    unit: 'hosted-zone',
    description: 'per zone',
  },
  eventbridge: {
    serviceType: 'eventbridge',
    displayName: 'EventBridge',
    category: 'messaging',
    defaultMonthly: 1.0,
    pricingModel: 'on-demand',
    unit: 'events',
    description: '1M events',
  },
  athena: {
    serviceType: 'athena',
    displayName: 'Athena',
    category: 'analytics',
    defaultMonthly: 5.0,
    pricingModel: 'on-demand',
    unit: 'TB-scanned',
    description: '1TB scanned',
  },
  glue: {
    serviceType: 'glue',
    displayName: 'Glue',
    category: 'analytics',
    defaultMonthly: 4.4,
    pricingModel: 'on-demand',
    unit: 'DPU-hours',
    description: '10 DPU-hrs',
  },
  emr: {
    serviceType: 'emr',
    displayName: 'EMR',
    category: 'analytics',
    defaultMonthly: 138.0,
    pricingModel: 'on-demand',
    unit: 'instance-hour',
    description: '3 node cluster',
  },
  cognito: {
    serviceType: 'cognito',
    displayName: 'Cognito',
    category: 'security',
    defaultMonthly: 0.0,
    pricingModel: 'on-demand',
    unit: 'MAU',
    description: 'Free <50K MAU',
  },
  vpc: {
    serviceType: 'vpc',
    displayName: 'VPC',
    category: 'networking',
    defaultMonthly: 32.4,
    pricingModel: 'on-demand',
    unit: 'NAT gateway',
    description: 'VPC + NAT',
  },
  iam: {
    serviceType: 'iam',
    displayName: 'IAM',
    category: 'security',
    defaultMonthly: 0.0,
    pricingModel: 'on-demand',
    unit: 'free',
    description: 'No cost',
  },
  alb: {
    serviceType: 'alb',
    displayName: 'ALB',
    category: 'networking',
    defaultMonthly: 16.2,
    pricingModel: 'on-demand',
    unit: 'LCU-hour',
    description: 'per ALB',
  },
  waf: {
    serviceType: 'waf',
    displayName: 'WAF',
    category: 'security',
    defaultMonthly: 5.0,
    pricingModel: 'on-demand',
    unit: 'web-ACL',
    description: 'per ACL',
  },
};

/**
 * GCP pricing data — estimated monthly costs for common service types.
 * Values are based on typical pricing in us-central1.
 */
export const gcpPricingData: Record<string, PricingEntry> = {
  'compute-engine': {
    serviceType: 'compute-engine',
    displayName: 'Compute Engine',
    category: 'compute',
    defaultMonthly: 24.46,
    pricingModel: 'on-demand',
    unit: 'instance-hour',
    description: 'e2-medium',
  },
  'cloud-run': {
    serviceType: 'cloud-run',
    displayName: 'Cloud Run',
    category: 'compute',
    defaultMonthly: 18.0,
    pricingModel: 'on-demand',
    unit: 'vCPU-second',
    description: '10M requests',
  },
  gke: {
    serviceType: 'gke',
    displayName: 'GKE',
    category: 'compute',
    defaultMonthly: 72.0,
    pricingModel: 'on-demand',
    unit: 'cluster-hour',
    description: 'Autopilot small',
  },
  'cloud-storage': {
    serviceType: 'cloud-storage',
    displayName: 'Cloud Storage',
    category: 'storage',
    defaultMonthly: 20.8,
    pricingModel: 'on-demand',
    unit: 'GB-month',
    description: '1TB standard',
  },
  bigquery: {
    serviceType: 'bigquery',
    displayName: 'BigQuery',
    category: 'analytics',
    defaultMonthly: 6.25,
    pricingModel: 'on-demand',
    unit: 'TB-processed',
    description: '1TB on-demand',
  },
  'cloud-sql': {
    serviceType: 'cloud-sql',
    displayName: 'Cloud SQL',
    category: 'database',
    defaultMonthly: 70.0,
    pricingModel: 'on-demand',
    unit: 'instance-hour',
    description: 'db-custom-2-8192',
  },
  'cloud-functions': {
    serviceType: 'cloud-functions',
    displayName: 'Cloud Functions',
    category: 'compute',
    defaultMonthly: 4.0,
    pricingModel: 'on-demand',
    unit: 'invocations',
    description: '10M invocations',
  },
  pubsub: {
    serviceType: 'pubsub',
    displayName: 'Pub/Sub',
    category: 'messaging',
    defaultMonthly: 4.0,
    pricingModel: 'on-demand',
    unit: 'GB-processed',
    description: '100GB/mo',
  },
  'cloud-spanner': {
    serviceType: 'cloud-spanner',
    displayName: 'Cloud Spanner',
    category: 'database',
    defaultMonthly: 650.0,
    pricingModel: 'on-demand',
    unit: 'node-hour',
    description: '1 node',
  },
  bigtable: {
    serviceType: 'bigtable',
    displayName: 'Bigtable',
    category: 'database',
    defaultMonthly: 468.0,
    pricingModel: 'on-demand',
    unit: 'node-hour',
    description: '1 node SSD',
  },
  alloydb: {
    serviceType: 'alloydb',
    displayName: 'AlloyDB',
    category: 'database',
    defaultMonthly: 130.0,
    pricingModel: 'on-demand',
    unit: 'vCPU-hour',
    description: '2 vCPU primary',
  },
  'vertex-ai': {
    serviceType: 'vertex-ai',
    displayName: 'Vertex AI',
    category: 'compute',
    defaultMonthly: 50.0,
    pricingModel: 'on-demand',
    unit: 'prediction-hour',
    description: 'n1-standard-2 endpoint',
  },
  'cloud-build': {
    serviceType: 'cloud-build',
    displayName: 'Cloud Build',
    category: 'compute',
    defaultMonthly: 0.0,
    pricingModel: 'on-demand',
    unit: 'build-minute',
    description: 'Free tier',
  },
  vpc: {
    serviceType: 'vpc',
    displayName: 'VPC',
    category: 'networking',
    defaultMonthly: 32.09,
    pricingModel: 'on-demand',
    unit: 'NAT gateway',
    description: 'VPC + Cloud NAT',
  },
  'cloud-load-balancing': {
    serviceType: 'cloud-load-balancing',
    displayName: 'Cloud Load Balancing',
    category: 'networking',
    defaultMonthly: 18.0,
    pricingModel: 'on-demand',
    unit: 'forwarding-rule',
    description: 'Global HTTP(S)',
  },
  'cloud-cdn': {
    serviceType: 'cloud-cdn',
    displayName: 'Cloud CDN',
    category: 'networking',
    defaultMonthly: 8.0,
    pricingModel: 'on-demand',
    unit: 'GB-served',
    description: '100GB cache egress',
  },
  'cloud-armor': {
    serviceType: 'cloud-armor',
    displayName: 'Cloud Armor',
    category: 'security',
    defaultMonthly: 5.0,
    pricingModel: 'on-demand',
    unit: 'policy',
    description: 'per policy',
  },
  'cloud-nat': {
    serviceType: 'cloud-nat',
    displayName: 'Cloud NAT',
    category: 'networking',
    defaultMonthly: 32.09,
    pricingModel: 'on-demand',
    unit: 'gateway-hour',
    description: 'NAT gateway',
  },
  memorystore: {
    serviceType: 'memorystore',
    displayName: 'Memorystore',
    category: 'database',
    defaultMonthly: 80.0,
    pricingModel: 'on-demand',
    unit: 'GB-hour',
    description: '4GB Redis HA',
  },
  'secret-manager': {
    serviceType: 'secret-manager',
    displayName: 'Secret Manager',
    category: 'security',
    defaultMonthly: 0.06,
    pricingModel: 'on-demand',
    unit: 'secret-version',
    description: 'per secret',
  },
  'cloud-kms': {
    serviceType: 'cloud-kms',
    displayName: 'Cloud KMS',
    category: 'security',
    defaultMonthly: 0.03,
    pricingModel: 'on-demand',
    unit: 'key-version',
    description: 'per key',
  },
  'cloud-monitoring': {
    serviceType: 'cloud-monitoring',
    displayName: 'Cloud Monitoring',
    category: 'monitoring',
    defaultMonthly: 0.0,
    pricingModel: 'on-demand',
    unit: 'free',
    description: 'Included with GCP',
  },
  'cloud-logging': {
    serviceType: 'cloud-logging',
    displayName: 'Cloud Logging',
    category: 'monitoring',
    defaultMonthly: 0.5,
    pricingModel: 'on-demand',
    unit: 'GB-ingested',
    description: 'After free 50GB',
  },
  'artifact-registry': {
    serviceType: 'artifact-registry',
    displayName: 'Artifact Registry',
    category: 'storage',
    defaultMonthly: 0.1,
    pricingModel: 'on-demand',
    unit: 'GB-month',
    description: 'per GB stored',
  },
  'cloud-iam': {
    serviceType: 'cloud-iam',
    displayName: 'Cloud IAM',
    category: 'security',
    defaultMonthly: 0.0,
    pricingModel: 'on-demand',
    unit: 'free',
    description: 'No cost',
  },
};

/**
 * Get pricing entry for a service type across both clouds.
 */
export function getPricingForService(
  serviceType: string,
  provider: 'aws' | 'gcp' | string
): PricingEntry | undefined {
  if (provider === 'aws') {
    return awsPricingData[serviceType];
  }
  if (provider === 'gcp') {
    return gcpPricingData[serviceType];
  }
  return undefined;
}
